### ISSUE TITLE
Strong-mode errors in common pub packages

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dev_compiler#480]
This is an umbrella issue to keep track of packages that need an update before we can compile "real-world" angular2 applications:

- [ ] [package:angular2](http://pub.dartlang.org/packages/angular2) (https://github.com/angular/angular/issues/7356)
- [x] [package:collection](http://pub.dartlang.org/packages/collection) (https://github.com/dart-lang/collection/issues/23)
- [x] [package:protobuf](http://pub.dartlang.org/packages/protobuf) (https://github.com/dart-lang/dart-protobuf/issues/54)
- [ ] [package:quiver](http://pub.dartlang.org/packages/quiver) (https://github.com/google/quiver-dart/issues/285)

**Comment by vsmenon** [comment]
@skybrian

**Comment by ochafik** [comment]
Note: even when projects are made clean, would be nice to ensure they remain that way. Quiver already runs the analyzer in travis (just needs `--strong` after it's fixed), but we may want to suggest a config like the following (untested) for the other projects:
```yaml
language: dart
dart:
  - stable
  - dev
script:
  - dartanalyzer --strong `find lib -name '*.dart'`
  - pub run test:test
matrix:
  allow_failures:
    - dart: dev
```
@leafpetersen WDYT? (this allows for some temporary dev breakages)
